# Exploratory Data Analysis & Profiling

In [40]:
import os
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

## 🔍 Observations

- The dataset contains **114,000 tracks** and **21 columns**, providing a solid volume of data for analysis.
- Most fields are **100% complete**, while only **3 text columns** (`artists`, `album_name`, and `track_name`) contain missing values.
- The audio features, popularity, duration, and other numerical attributes are **fully populated**, supporting reliable analysis.
- The dataset combines **track information, musical characteristics, and popularity**, making it suitable for exploring patterns and relationships in Spotify music data.
- Overall, the dataset presents **good data quality** and provides a strong foundation for the next stages of analysis.

In [41]:


# Load Spotify data
spotify_df = pd.read_csv("../data/raw/spotify_dataset.csv")

# 1. Structural Overview
print(f"Spotify Dataset Shape: {spotify_df.shape}")
print("-" * 50)
spotify_df.info()

Spotify Dataset Shape: (114000, 21)
--------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 114000 entries, 0 to 113999
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        114000 non-null  int64
 1   track_id          114000 non-null  str
 2   artists           113999 non-null  str
 3   album_name        113999 non-null  str
 4   track_name        113999 non-null  str
 5   popularity        114000 non-null  int64
 6   duration_ms       114000 non-null  int64
 7   explicit          114000 non-null  bool
 8   danceability      114000 non-null  float64
 9   energy            114000 non-null  float64
 10  key               114000 non-null  int64
 11  loudness          114000 non-null  float64
 12  mode              114000 non-null  int64
 13  speechiness       114000 non-null  float64
 14  acousticness      114000 non-null  float64
 15  instrumentalness  114000 non-null  float64
 16  liveness          114000 non-null  float64
 17  valence           114000 non-null  float64
 18  tempo             114000 non-null  float64
 19  time_signature    114000 non-null  int64
 20  track_genre       114000 non-null  str
dtypes: bool(1), float64(9), int64(6), str(5)
memory usage: 17.5 MB

### Null values

In [42]:
spotify_df.isnull().sum()

Unnamed: 0          0
track_id            0
artists             1
album_name          1
track_name          1
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

In [43]:
# Missing Values Analysis (Spotify)
# Missing Values Analysis (Spotify)
spotify_nulls = spotify_df.isnull().sum()

print("Missing values per column:")
spotify_nulls = spotify_df.isnull().sum()
print(spotify_nulls[spotify_nulls > 0])

Missing values per column:
artists       1
album_name    1
track_name    1
dtype: int64

In [44]:


# Null values analysis
df_sp = spotify_df

nulls_sp = df_sp.isnull().sum()
nulls_percentage_sp = (nulls_sp / len(df_sp)) * 100
df_null_sp = pd.DataFrame({'Nulls': nulls_sp, 'Percentage (%)': nulls_percentage_sp})
print(df_null_sp)

# Show only columns with null value
display(df_null_sp[df_null_sp['Nulls'] > 0].sort_values(by='Percentage (%)', ascending=False))

                  Nulls  Percentage (%)
Unnamed: 0            0        0.000000
track_id              0        0.000000
artists               1        0.000877
album_name            1        0.000877
track_name            1        0.000877
popularity            0        0.000000
duration_ms           0        0.000000
explicit              0        0.000000
danceability          0        0.000000
energy                0        0.000000
key                   0        0.000000
loudness              0        0.000000
mode                  0        0.000000
speechiness           0        0.000000
acousticness          0        0.000000
instrumentalness      0        0.000000
liveness              0        0.000000
valence               0        0.000000
tempo                 0        0.000000
time_signature        0        0.000000
track_genre           0        0.000000

            Nulls  Percentage (%)
artists         1        0.000877
album_name      1        0.000877
track_name      1        0.000877

In [45]:
spotify_df[spotify_df["artists"].isnull()]

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
65900,65900,1kR4gIb7nGxHPI3D2ifs59,NaN,NaN,NaN,0,0,False,0.501,0.583,...,-9.46,0,0.0605,0.69,0.00396,0.0747,0.734,138.391,4,k-pop

## Missing Values Analysis (Spotify)

In [46]:
duplicated_values = spotify_df.duplicated()
duplicated_values.sum()

np.int64(0)

In [47]:
total_duplicated_sp = spotify_df.duplicated().sum()
print(f"{total_duplicated_sp} rows were found that were exactly the same")

if total_duplicated_sp > 0:
    # sample of some duplicated rows
    display(spotify_df[spotify_df.duplicated(keep=False)].sort_values(by='track_id').head(4))

0 rows were found that were exactly the same